### ISSUE TITLE
Visitor carts are captured whereas I had not added the product as a guest user.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-abandoned-cart#392]
I am facing the issue where visitor carts are captured whereas I had not added the product as a guest user.

1. I have logged-in to the site as an Admin in Chrome
2. Added to 2 products to the cart as an admin user
3. Then closed browser ( Chrome will remember history )
4. Again open the same browser without clearing cache
5. Opened the site as a guest user where cart will have the products which I had added earlier as a logged-in user. I did not visit any page of the site.
6. Then I have checked by login to the site that visitor cart was added.

Screenshot: http://prntscr.com/l409ia

Scre

**Comment by Chetna1510** [comment]
This issue was coming as we had PHP sessions started. We have removed it. Hence, I am closing this issue.

Commit: 9a958d16ccc550bd3adde30de3e04b45ca2d40f1

**Comment by apeksha10** [comment]
I am able to replicate the same issue with latest git copy
Follow the same steps issue mention

Abandoned order tab screenshot:  https://www.screencast.com/t/YXVJDrsA
Settings: https://www.screencast.com/t/L8LNy3lG


Hence re-open this issue

**Comment by PradeepTyche** [comment]
Not happening.

https://www.screencast.com/t/2UKZMQXbJ3UD

**Comment by PradeepTyche** [comment]
The cart is added as Abandoned cart from the logged in user, not as Visitor. You can see the email and username in the video
