### ISSUE TITLE
"This order was abandoned & subsequently recovered." note display on woo-order page when I change the order status "Pending" to "Cancel" 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#464]
Testing #428
**Describe the bug**
"This order was abandoned & subsequently recovered."note display on woo-order page when I change the order status from "Pending" to "Cancelled"

Same steps follow as #428 issue has

**Expected behavior**
Changing the order status then the woo-order note is not display

**Screenshots or Video**
https://www.screencast.com/t/IToMeKdfuz

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/a68MfwiaDx

https://www.screencast.com/t/Tvxl5Nk8ALa

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/sau3EVnlaIsx
