### ISSUE TITLE
Showing the wrong quantities in the Abandoned Cart Reminder email

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-abandoned-cart#469]
**Describe the bug**
Product quantity is showing wrong in the Abandoned Cart REminder email when we use WooCommece Min/Max quantities plugin. 

**To Reproduce**
1. I have installed WooCommece Min/Max quantities plugin
2. added minimum quantities 3 for product "classic duo pink dots" 
3. Then abandoned a cart with 3 quantities for the same product and abandoned a cart as a guest user
4. It is showing only 1 quantity in email http://prntscr.com/n33nti whereas Abandoned Order details showing 3 quantities: http://prntscr.com/n33om5

**Expected behavior**
In the abandoned cart reminder email, it should be displayed 3 quantities.

**Isolating the problem (mark completed items with an [x]):**
 [ ] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by PradeepTyche** [comment]
Not happening with min/max quantities installed and with the same conditions applied above.

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/PjsIlGWrolL

Using Berocket min max quantity plugin
https://wordpress.org/plugins/minmax-quantity-for-woocommerce/
