### ISSUE TITLE
Seeing random numbers on the Abandoned Carts page on a client site

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/woocommerce-abandoned-cart#470]
**Describe the bug**
I am seeing random single digit numbers below the Abandoned order numbers on a client's website. I noticed this when debugging another issue related to the Order Delivery Date Pro plugin for this client. I don't think those numbers should be there, instead it should show the details of the customer perhaps who abandoned the cart?

**Screenshots or Video**
https://screencast.com/t/uE9FrAt7J

**Comment by dhruvins** [comment]
@ashokrane actually these are Abandoned Order ID's like `17208`, `17209`, `17210` etc .. the numbers should be wrapped in a better way or the headers if reduced might fit correctly

**Comment by PradeepTyche** [comment]
The numbers are wraped correctly. They dont flow to next line.

**Comment by PradeepTyche** [comment]
Closing after review

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/Ml4F9lmN53

numbers coming in single line.
