### ISSUE TITLE
With the WP Engine, the 500 Error is coming when the user login to the admin end of the site.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#471]
When logging into the admin panel, the 500 server error is appearing. Retyping the admin URL allows to log in. This error is occurring on the client's site who is using WP Engine.

**To Reproduce**
1. Try to login to the admin end of the site.
2. You will get 500 error.
3. When you refresh the screen, it will show the dashboard of the site.
Screenshot:

ERROR appearing in the debug log file: 

PHP Fatal error: Uncaught Error: Using $this when not in object context in /nas/content/live/sliquid/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php:210\nStack trace:\n#0 [internal function]: woocommerce_abandon_cart_lite::wcal_remove_action_hook('wpengine')\n#1 /nas/content/live/sliquid/wp-includes/class-wp-hook.php(288): call_user_func_array(Array, Array)\n#2 /nas/content/live/sliquid/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)\n#3 /nas/content/live/sliquid/wp-includes/plugin.php(465): WP_Hook->do_action(Array)\n#4 /nas/content/live/sliquid/wp-includes/user.php(114): do_action('wp_login', 'wpengine', Object(WP_User))\n#5 /nas/content/live/sliquid/wp-login.php(929): wp_signon(Array, true)\n#6 {main}\n thrown in /nas/content/live/sliquid/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php on line 210

**NOTE: This issue is appearing on client's site which is using WP Engine. So we are unable to replicate it at our end.**

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Comment by pinalj** [comment]
The only reason such an issue would occur is if our plugin is not loaded correctly. Since no clients have reported anything similar recently and we're unable to replicate it at our end, closing the issue.

**Comment by pinalj** [comment]
Unable to replicated
