### ISSUE TITLE
Abandoned Cart Details are not showing on the Abandoned Order Details page

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-abandoned-cart#472]
**Describe the bug**
The issue was reported by the client that any details are not showing on the Abandoned Orders View page.

**To Reproduce**
I am not able to reproduce the issue.

**Expected behavior**
It should display details of Abandoned Carts.

**Screenshots or Video**
http://prntscr.com/n9dv96

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**WordPress Environment**
WordPress:		5.1.1
PHP                         7.1.27
WooCommerce	3.5.5
```
**Additional context**
Add any other context about the problem here.

**Comment by pinalj** [comment]
Since the issue was raised, we have moved to the abandoned cart details popup view, hence closing the issue. Please reopen if replicated.

**Comment by pinalj** [comment]
Unable to replicate
