### ISSUE TITLE
20% off coupon code email does not receive after click on "Allow" button

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#473]
Describe the bug
20% off coupon code email does not receive after click on "Allow" button

see the screenshot: https://www.screencast.com/t/XHTviIRTpYR

**Comment by pinalj** [comment]
Unable to replicate the issue. The issue has also not been reported by any client recently.

**Comment by pinalj** [comment]
Raised & fixed the error displayed with PHP 8.0.6.
