### ISSUE TITLE
The {{products.cart}} merge tag is not working in the Abandoned Cart Reminder email

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/woocommerce-abandoned-cart#474]
**Describe the bug**
The client has reported the issue where {{products.cart}} merge tag is not working in the Abandoned Cart Reminder email.
I was also able to replicate it on the client's site. It is working fine in the test email.

**To Reproduce**
1. I have abandoned a cart as a guest user. 
2 Then I received an abandoned cart reminder email. In the email "Product no longer exist" message is showing instead of Product Table. 

**Expected behavior**
It should display a product information table.

**Screenshots or Video**
Screenshot of email: http://prntscr.com/nbc1wr
Screenshot of template: http://prntscr.com/nbc218
Screenshot of Abandoned Cart: http://prntscr.com/nbc29c

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Comment by pinalj** [comment]
This issue has not been reported recently by any client. Please reopen if replicated.

**Comment by pinalj** [comment]
Unable to replicate with PHP 7.4 & PHP 8.0.6
