### ISSUE TITLE
Abandoned order time and Recovered order time shows same time.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#479]
**Describe the bug**
Abandoned order time and Recovered order time shows the same time.
On my local WooCommerce version is 3.5.7 
**To Reproduce**
1. An abandoned cart as guest users
2. Reminder email received
3. Click on the Checkout link
4. Increase the product qty
5. Place the order

**Screenshots or Video**
https://www.screencast.com/t/VLollbOx

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by PradeepTyche** [comment]
Not happening

**Comment by pinalj** [comment]
Unable to replicate with the latest versions of WP, WC & AC Lite. Hence closing.

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/daOYgQXc

Timings are different after increasing quantity in the cart.
