### ISSUE TITLE
Default email template does not appear when I run Fresh install on multi site

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#537]
**Describe the bug**
Default email template does not appear when I run Fresh install

created a new child site on multisite but no Default email template was there which is wrong
https://www.screencast.com/t/iAZozjk5Gf

**Comment by pinalj** [comment]
When a new child site is created after the plugin has been installed & activated on the network, the plugin tables are not present on the new child site. Hence the issue. 

This can be fixed in a future release.

**Comment by apeksha10** [comment]
Steps to be follow
1. On the parent site, the Network is activated.
2. Create a new child site and go to woocommerce -abandoned cart menu. 
Here Default template is not seen

**Comment by apeksha10** [comment]
This is a very old issue and none of clients has asked for this bug

Hence I have closed this issue. We can re-open if any client has come up with this issue.
