### ISSUE TITLE
Not able to Add new email template on multi site

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#538]
**Describe the bug**
Not able to Add new email template on multi-site

**To Reproduce**
1. Create a new child site 
2. Try to add new email template but After click on Save button that email template does not get saved  

**Screenshots or Video**
https://www.screencast.com/t/3tBnyyIOyFUt

**Comment by pinalj** [comment]
When a new child site is created after the plugin has been installed & activated on the network, the plugin tables are not present on the new child site. Hence the issue. 

This can be fixed in a future release.

**Comment by apeksha10** [comment]
Steps to be follow

On the parent site, the Network is activated.
Create a new child site and go to woocommerce -abandoned cart menu.
Here Default template is not seen

**Comment by apeksha10** [comment]
This is a very old issue and none of the clients has asked for this bug

Hence I have closed this issue. We can re-open if any client has come up with this issue.
