### ISSUE TITLE
Autofill in “test email” with admin email

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#602]
**Is your feature request related to a problem? Please describe.**
Autofill in “test email” with admin email

**Describe the solution you'd like**
As per client "Can you please automatically fill in the test email field with the admin email provided in the “Settings” section of the plugin? It’s a bit bothering to always fill in the email every time."

I think this is a good feature we should implement this feature.

https://wordpress.org/support/topic/improvement-auto-fill-in-test-email-with-admin-email/

**Comment by pinalj** [comment]
I think the best approach here would be to pre-populate the field with the logged in user's email instead of the admin.
