### ISSUE TITLE
Successful message even if test email is empty

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#603]
**Describe the bug**
The successful message even if the test email is empty.

After clicking "Send a test email" successful message display even if the test email field is empty

see the video : 
https://www.screencast.com/t/WLuGfN4Xd04

https://wordpress.org/support/topic/successful-message-even-if-test-email-is-empty/

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/EHwNYxLfQ 
Warning message below the email field if there is no vaild email,
