### ISSUE TITLE
Reminder email shows SKU with product title

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#604]
**Describe the bug**
Reminder email shows SKU with product title

**To Reproduce**
1. Variable product with SKU 
2. Reminder email received with the product name and SKU 

https://www.screencast.com/t/MdO52H3x

As discussed with Dhruvin, we can provide 1 filter.
 
https://wordpress.org/support/topic/why-the-name-of-the-product-shown-in-email-includes-sku/

**Comment by pinalj** [comment]
The filter to allow the site admin to hide the SKU in reminder emails has been included. Hence closing.
