### ISSUE TITLE
Compatibility with the WooCommerce Multi-Currency Premium plugin.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-abandoned-cart#639]
When the WooCommerce Multi-Currency plugin is activated, when a new currency is added with that plugin then we are not able to see the cart prices on the abandoned orders list. None of the details are shown. Screenshot for the same: https://prnt.sc/t47yol.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/17845

Plugin copy: 
[codecanyon-cUxVxB2C-woocommerce-multi-currency-wordpress-plugin.zip](https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/files/4812790/codecanyon-cUxVxB2C-woocommerce-multi-currency-wordpress-plugin.zip)

**Comment by pinalj** [comment]
This is not a request which is in high demand, hence will not be considered for now. Closing.
