### ISSUE TITLE
Reminder email doesn't scroll down in the Mac in the Mail app.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#653]
**Describe the bug**
Reminder email doesn't scroll down in the Mac in the Mail app.

**Expected behavior**
We should be able to scroll the reminder email in the Mac in the Mail app.

The client has reported this issue on the forum. I haven't tried to replicate this issue yet as we need to check this by setting up the Mail app set up in the Mac. 

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

https://wordpress.org/support/topic/email-doesnt-scroll-in-mac-mail-app/

**Comment by pinalj** [comment]
Checked this in the Mail app on iPad. The email is scrolling fine. Hence closing the issue.

**Comment by pinalj** [comment]
Checked this in the Mail app on iPad. Mail app on Android as well was tested. No issues found.
