### ISSUE TITLE
The reminder email was not being sent for guest carts.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#654]
**Describe the bug**
The reminder email was not being sent for guest carts on a client's site.

**To Reproduce**
1. Abandon a cart as a guest user. The cart is being tracked fine but the reminder email is not being sent.
However, the reminder email was being sent for registered user carts. 

This issue was coming only on a client's site.

**Screenshots or Video**

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

https://tychesoftwares.freshdesk.com/a/tickets/18350

**Comment by pinalj** [comment]
The issue was that the guest user IDs were being logged as 1,2,3 instead of 63000000,63000001 and so on. The same has been fixed and things are working fine on the site now.
