### ISSUE TITLE
Merge tag does not get replaced with creating a new email template.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#670]
**Describe the bug**
Merge tag does not get replaced with creating a new email template.

**To Reproduce**
1. Create a new email template with all merged tags. https://www.screencast.com/t/ZjxEQhJ2sIjV
2. try to test Preview email but the merge tag does not get replaced.  https://www.screencast.com/t/d5aVcs55gz
https://www.screencast.com/t/qmL4ekEa

Note: The above issue is replicated with or without this setting "Use WooCommerce Template Style" 

**Expected behavior**
Merge tag should be replaced in the Preview email template

**Comment by pinalj** [comment]
The below merge tags are not replaced with dummy content in preview emails:
1. cart link
2. abandoned cart time
3. unsubscribe link
Since this is an existing issue, moving it to the next update.
