### ISSUE TITLE
We should add some hooks or feature that allows users to add CSS changes easily in the template.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#700]
One client wants to change our cart table's text color because as per him, the background is dark and the default table color is already dark. Hence he wants to change the abandoned cart table's text color.

I have talked with the developer and they said, it is not possible to edit it easily. This will need code changes. So it would be nice if we can add some hooks or some feature which will allow users to add CSS changes easily in the template.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22462

**Comment by pinalj** [comment]
No new hooks have been added. Instead we have changed the default template CSS code to make it responsive. Style changes can be added directly in the style sheet present in the email template to accommodate CSS changes as needed.

**Comment by apeksha10** [comment]
Discussed this with @pinalj and even font color display fine.

So I am putting a fixed label.
