### ISSUE TITLE
Fatal Error when recovering an abandoned cart

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/woocommerce-abandoned-cart#714]
A client has reported a fatal error when recovering a cart. The steps etc. are unclear, but we will need to check with Paypal and one more payment medium to be sure things are working smoothly.

https://wordpress.org/support/topic/fatal-error-call-to-a-member-function-add_order_note/

**Comment by pinalj** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-abandoned-cart/pull/713/commits/1faf1e4dfa716b3acb9077ba2e947e56e034afe0

**Comment by apeksha10** [comment]
As per Pinal "Fatal error when recovering abandoned carts - pls note that we've not had a chance to replicate this issue. I've simply applied a fix based on the error log shared by the client. So it would be great if you can run some tests with Paypal and one more payment medium"

So I tried to recovered order using Stripe Payment  gateway and things are working fine

Hence I have put a fixed label.
