### ISSUE TITLE
Support 'On Hold' orders where the payment does not complete

### ISSUE THREAD

**Issue by anthonygreat** [TycheSoftwares/woocommerce-abandoned-cart#722]
Count 'On Hold' orders that don't have a complete payment as part of abandoned carts (i.e. where the payment fails or didn't complete).

**Comment by anthonygreat** [comment]
https://tychesoftwares.freshdesk.com/a/tickets/27167

**Comment by pinalj** [comment]
In most cases, when a WC order has the status 'On hold', the order is considered placed and not abandoned. No reminders can be sent out for such orders.

For WC Order status 'Pending payment' - no reminder is sent. The same is also not listed in the Abandoned Orders tab once the scheduled action is run. The abandoned cart is being marked with cart_ignored = 1

**Comment by pinalj** [comment]
Emails should be sent for Pending & Failed payment statuses. They are being sent in the Pro version and the same should be the case for Lite version as well.
