### ISSUE TITLE
Plugin throws me 500 (Internal Server Error) while I try to send a test email from the edit template page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#737]
**Describe the bug**
Plugin throws me 500 (Internal Server Error) while I try to send a test email from the edit template page.

**To Reproduce**
1. PHP 8.0 setup
2. Take a live copy that is 5.8.8
3. Go to edit email template page, I try to send test email but the plugin throws me 500 (Internal Server Error)
https://www.screencast.com/t/kwfViIufk

**Expected behavior**
Test email should be sent without any error.

Note: Reminder emails are received till the last half an hour but the abandoned order tab shows reminder email has been sent. https://www.screencast.com/t/ECKM8iv4

So here we need to check issues related to reminder emails which I raised on the Pro repository

**Comment by pinalj** [comment]
An error is logged in debug.log when we try to send the test email for the default template. The error points to Emogrifier library. This is used by WC for inline css in emails. Updating the library should most likely fix the issue. Until then, I have removed some CSS which was causing the error. The default template should be checked to ensure it is displayed fine across different screen sizes such as mobiles, tablets and laptops.
