### ISSUE TITLE
'Minutes' text does not appear on the email template listing page.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#752]
**Describe the bug**
'Minutes' text does not appear on the email template listing page.

**To Reproduce**
1. Upload the latest git copy
2. Go to the Email template tab and try to change the frequency of the email template
3. I have set 1 min and clicked on the Update changes button
4. Email template listing page, 'Min' test does not appear.
see the screenshot: https://www.screencast.com/t/SiRbvJTaaauV
https://www.screencast.com/t/i12Z7dxzdoUw

Here, the "Day' and 'Hour' texts appear fine.  https://www.screencast.com/t/qV3Iu5Lr5AA
https://www.screencast.com/t/yF70sz17Le

**Expected behavior**
Minutes text should appear on the email template listing page

**Comment by PradeepTyche** [comment]
https://www.screencast.com/t/7bUhir7LH
