### ISSUE TITLE
A reminder email is not received after uploading the latest git copy.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#753]
**Describe the bug**
A reminder email is not received after uploading the latest git copy.

**To Reproduce**
1. Upload the latest git copy
2. Change the email template frequncy. In my case, I have set 1 min
3. Abandoned 1 guest cart 
4. Reminder email does not receive.

DB screenshot: https://www.screencast.com/t/3qLkAUXfE

**Expected behavior**
A reminder email should be received after uploading the latest git copy.

**Comment by PradeepTyche** [comment]
Mail sent after taking latest version
