### ISSUE TITLE
Test and reminder emails are being sent in plain text with the WP Better Emails plugin.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#775]
**Describe the bug**
Test and reminder emails are being sent in plain text with the WP Better Emails plugin.

**To Reproduce**
1. Activate the WP Better Emails plugin on the site along with our AC lite plugin.
2. If you sent a test email or the cart reminder email will be sent to users, it will be shown as plain text emails.

**Expected behavior**
Test and reminder emails should show in HTML form.

**Screenshots or Video**
https://www.screencast.com/t/V2RjSWfD9dto

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/33926

**Comment by pinalj** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-abandoned-cart/pull/785/commits/86b283aadec029e37a717b3022666feccc90a3a1
