### ISSUE TITLE
The "Enable GDPR Notice" checkbox is disabled even if I have set some text on that GDPR fields before updating the plugin. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#794]
**Describe the bug**
The "Enable GDPR Notice" checkbox is disabled even if I have set some text on that GDPR fields before updating the plugin. 

**To Reproduce**
1. Take a live copy 
2. Set some text on the GDPR fields
3. Update the plugin, and I noticed the "Enable GDPR Notice" checkbox is disabled
https://www.screencast.com/t/YaCGXSoAp9G

**Expected behavior**
The "Enable GDPR Notice" checkbox is should be enabled if users set some text on that GDPR field before updating the plugin.

**Comment by pinalj** [comment]
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/pull/793/commits/607b84da81910da31eac88ededd9001dfe3d53ee
