### ISSUE TITLE
"Link Expired" message appears when I try to copy the checkout link from webhook.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#795]
**Describe the bug**
"Link Expired" message appears when I try to copy the checkout link from webhook.

**To Reproduce**
1. Cart is abandoned ( logged in users/ Guest users )
2. After the cut off time is passed, a webhook is created 
3. Copy the checkout link from the webhook and open it to another browser. https://www.screencast.com/t/FOedyI1th6y
4. The plugin throw me a "Link Expired" message. 

**Expected behavior**
The checkout link should be redirected to the checkout page for that cart.

**Comment by pinalj** [comment]
This fix includes changes in the links generated for reminder emails as well. So links from both sources should be tested when recovering carts.
