### ISSUE TITLE
Multiple events are created when I try to abandon the cart as logged-in users.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#796]
**Describe the bug**
Multiple events are created when I try to abandon the cart as logged-in users. 

**To Reproduce**
1. Abandoned the cart as logged in users
2. Multiple events are created ( https://www.screencast.com/t/f865VwdDl)

**Expected behavior**
Only 1 webhook should be generated after abandoning the cart as logged-in users.

**Comment by pinalj** [comment]
Unable to replicate. I have abandoned a total of 3 carts in a span of 5 mins. 1 registered user cart & 2 guest user carts.

1. Abandoned Carts: https://www.screencast.com/t/k7JGihhgE
2. Delivery URL: https://www.screencast.com/t/pQfV5USykS
No extra events have been created.

**Comment by apeksha10** [comment]
With the latest git copy, I am able to replicate the above issue 

Steps:
1. I am working on woo_apeksha
2. Try to abandon as logged in users 
3. After cut-off time passed, multiple webhook are fired.
see the screenshot : https://www.screencast.com/t/ciXYwAxt2xA

Hence I have re-open this issue.
