### ISSUE TITLE
Order Received page shows some notice. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#806]
**Describe the bug**
Order Received page shows some notice. 

**To Reproduce**
1. Fresh Installation 
2. Create 2 email templates.  https://www.screencast.com/t/jT3mxkVTjA5
3. Reminder email received 
4. Try to recover the cart and the order received page shows some error.
https://www.screencast.com/t/UsBrJny6mQQ9
https://www.screencast.com/t/2tUtW3w4W

**Expected behavior**
No error must be thrown from our plugin.

**Comment by pinalj** [comment]
The issue is replicated when:
1. More than 1 reminder email has been sent
2. Guest user creates an account at Checkout
