### ISSUE TITLE
The second & third reminder emails are not receiving from the client site.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#809]
**Describe the bug**
The second & third reminder emails are not received from the client site. Only the first reminder email has been received.

**To Reproduce**

I have abandoned a guest user cart on the client site. I have received only one reminder email, not 2nd and 3rd reminder emails.
https://www.screencast.com/t/GkZxxlZzOt

https://www.screencast.com/t/8ypoB2muN1

This issue is client site-specific. I am not able to replicate this on our staging site.

**Expected behavior**
All reminder emails should receive to the customers who abandon the cart.

**Isolating the problem (mark completed items with an [x]):**
[x] This bug happens with only Abandoned cart pro plugin active
[x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
[x] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/37525

**Comment by pinalj** [comment]
Already fixed in version 5.12.0
