### ISSUE TITLE
Update the below documentation.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#814]
We have added the Coupon code merge tag in our email template settings. So please update it in the below documentation.

https://www.tychesoftwares.com/docs/docs/abandoned-cart-for-woocommerce-lite/different-merge-codes/

**Comment by tedioustanisha** [comment]
updated here: https://www.tychesoftwares.com/docs/woocommerce-abandoned-cart-lite/different-merge-codes?preview_id=627&preview_nonce=dba07a0456&_thumbnail_id=-1&preview=true
