### ISSUE TITLE
Add email type column in DB table for email templates

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/woocommerce-abandoned-cart#815]
**Is your feature request related to a problem? Please describe.**
Allow for the possibility of providing more email solutions (apart from reminders for carts) in the plugin

**Describe the solution you'd like**
1. Add a column in the email templates table as 'email_type'
2. By default the value for this column will be 'reminders'
3. The value should be set to 'reminders' for all new email templates & existing email templates for now.

**Comment by pinalj** [comment]
Reference issue: https://github.com/TycheSoftwares/woocommerce-abandon-cart-pro/issues/2897
Reference commit: https://github.com/TycheSoftwares/woocommerce-abandon-cart-pro/commit/16abfc4bf35666124f05c5a6bb1c246b808a39a7

**Comment by apeksha10** [comment]
After taking the latest git copy, I am not able to see any changes in the DB code

https://www.screencast.com/t/2fIC98EP5H

Hence I have re-open this issue

**Comment by apeksha10** [comment]
With the latest git copy, I got a column but with a blank value.
https://www.screencast.com/t/JpjkjH4QvSr

Debug log error :
[22-Aug-2022 09:49:29 UTC] PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function wpdb::update(), 2 passed in C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php on line 195 and at least 3 expected in C:\Users\User\Local Sites\local1\app\public\wp-includes\wp-db.php:2434
Stack trace:
#0 C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php(195): wpdb->update('wp_ac_email_tem...', Array)
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/issues/1 C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php(138): Wcal_Update::wcal_alter_tables('wp_', 0)
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/issues/2 C:\Users\User\Local Sites\local1\app\public\wp-content\plugins\woocommerce-abandoned-cart\class-wcal-update.php(85): Wcal_Update::wcal_process_db_update()
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/issues/3 C:\Users\User\Local Sites\local1\app\public\wp-includes\class-wp-hook.php(307): Wcal_Update::wcal_update_db_check()
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/issues/4 C:\Users\User\Local Sites\local1\app\public\wp-includes\class-wp-hook.php(331): WP_Hook->apply_fi in C:\Users\User\Local Sites\local1\app\public\wp-includes\wp-db.php on line 2434

Hence I have re-open this issue.
