### ISSUE TITLE
Update the screenshots in the below documentation.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#821]
We have added 2 new tabs in our AC plugin so we can update the screenshots in this documentation.

https://www.tychesoftwares.com/docs/docs/abandoned-cart-for-woocommerce-lite/recovered-orders/

**Comment by tedioustanisha** [comment]
updated here- https://www.tychesoftwares.com/docs/woocommerce-abandoned-cart-lite/recovered-orders?preview_id=612&preview_nonce=2189fdc61b&_thumbnail_id=-1&preview=true
