### ISSUE TITLE
Add a filter to remove the product image from the reminder email template.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#828]
**Describe the bug**
Add a filter in our plugin to remove the product image from the reminder email template.

**Additional context**

**Comment by apeksha10** [comment]
Re-opening this issue.

I have put the below filter on the function.php file

add_filter( 'wcal_reminder_email_product_header', 'change_name_header', 10, 1 );
function change_name_header( $name_header ) {
$name_header = 
return $name_header;
}

add_filter( 'wcal_reminder_email_prod_value', 'change_product_name', 10, 1 );
function change_product_name( $prod_col ) {
$prod_col= ''; // Hide the column.
return $prod_col;
}

https://www.screencast.com/t/xlpCsECw

Hence I have re-open this issue.

**Comment by pinalj** [comment]
Unable to replicate it. I've added code to hide both product image and product name.

`function change_img_header( $img_header ) {
	$img_header = ''; // Will hide the column.
	return $img_header;
}
add_filter( 'wcal_reminder_email_img_header', 'change_img_header', 10, 1 );

function change_img_value( $img_col ) {
	$img_col= ''; // Hide the column.
	return $img_col;
}
add_filter( 'wcal_reminder_email_image_value', 'change_img_value', 10, 1 );

function change_name_header( $name_header ) {
	$name_header = ''; // Will hide the column.
	return $name_header;
}
add_filter( 'wcal_reminder_email_product_header', 'change_name_header', 10, 1 );

function change_product_name( $prod_col ) {
	$prod_col= ''; // Hide the column.
	return $prod_col;
}
add_filter( 'wcal_reminder_email_prod_value', 'change_product_name', 10, 1 );`
