### ISSUE TITLE
An error appeared on the Multisite.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#833]
**Describe the bug**
The below error appeared on the Multisite after installing our plugin.
Notice: Undefined variable: blog_id in /wp-content/plugins/woocommerce-abandoned-cart/class-wcal-update.php on line 47

**Expected behavior**
There should be no such error appearing on the multisite.

**Screenshots or Video**

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Additional context**
https://wordpress.org/support/topic/undefined-variable-blog_id/

**Comment by pinalj** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-abandoned-cart/pull/832/commits/31b9dbc7986ca93474aab5be993ac8d4b7b2fb9f
