### ISSUE TITLE
Add hook to change the sender email address in recovery emails

### ISSUE THREAD

**Issue by pinalj** [TycheSoftwares/woocommerce-abandoned-cart#837]
**Is your feature request related to a problem? Please describe.**
A client wants to be able to change the sender email address for the notification email sent to the site admin on order recovery.

**Describe the solution you'd like**
Add a hook to achieve the above.

**Additional context**

**Comment by pinalj** [comment]
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/wiki/Recovery-Email-Hooks#change-recovery-email-sender

**Comment by apeksha10** [comment]
Re-opening this issue 

I have added the below filter 
add_filter( 'wcal_recovery_email_from', 'change_recovery_email_sender', 10, 1 );

function change_recovery_email_sender( $sender_email ) {
$sender_email = 'apekshayshah@gmail.com';
return $sender_email ;
}

Abandoned the cart as guest users (incognito mode)

**Comment by pinalj** [comment]
We use SMTP plugins on our local and staging sites. When a SMTP plugin is active, FROM field name etc. details are taken from the SMTP plugin settings and the hook code is overwritten.
