### ISSUE TITLE
Add a filter to change the colors in {{products.cart}}

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/woocommerce-abandoned-cart#852]
**Is your feature request related to a problem? Please describe.**
We should add a filter that will allow for the colors in {{products.cart}} to be changed when needed.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/50111](https://tychesoftwares.freshdesk.com/a/tickets/50111)

**Comment by pinalj** [comment]
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/wiki/Hooks-for-Reminder-Emails#add-custom-style-in-productscart-merge-tag-table
