### ISSUE TITLE
An error "There was an error creating the guest cart table for Abandoned Cart Lite for WooCommerce. Please contact the plugin author via email." appears on the back-end.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#860]
**Describe the bug**
An error "There was an error creating the guest cart table for Abandoned Cart Lite for WooCommerce. Please contact the plugin author via email." appears on the back end.

**To Reproduce**
I have asked for the access details for this client. We need to check this issue on a client site.

**Expected behavior**
Such an error should not appear.

**Screenshots or Video**

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/52146

**Comment by priyanka-tychesoftwares** [comment]
Another client is getting this error: https://tychesoftwares.freshdesk.com/a/tickets/52104

**Comment by priyanka-tychesoftwares** [comment]
One more client with this error: https://tychesoftwares.freshdesk.com/a/tickets/52202

**Comment by priyanka-tychesoftwares** [comment]
Another client: https://tychesoftwares.freshdesk.com/a/tickets/52207

**Comment by priyanka-tychesoftwares** [comment]
One more client is getting this error: https://tychesoftwares.freshdesk.com/a/tickets/52533

**Comment by oluisrael11** [comment]
A client reported this error - [https://tychesoftwares.freshdesk.com/a/tickets/52169](https://tychesoftwares.freshdesk.com/a/tickets/52169)

**Comment by oluisrael11** [comment]
Another user reported this error - [https://tychesoftwares.freshdesk.com/a/tickets/52295](https://tychesoftwares.freshdesk.com/a/tickets/52295)

**Comment by oluisrael11** [comment]
Another user reported this error — [https://tychesoftwares.freshdesk.com/a/tickets/52793](https://tychesoftwares.freshdesk.com/a/tickets/52793)

**Comment by oluisrael11** [comment]
Another user reported this error — [https://tychesoftwares.freshdesk.com/a/tickets/52669](https://tychesoftwares.freshdesk.com/a/tickets/52669)

**Comment by oluisrael11** [comment]
Another user reported this error — [https://tychesoftwares.freshdesk.com/a/tickets/52352](https://tychesoftwares.freshdesk.com/a/tickets/52352)

**Comment by oluisrael11** [comment]
One more user reported this issue — [https://tychesoftwares.freshdesk.com/a/tickets/52656](https://tychesoftwares.freshdesk.com/a/tickets/52656)

**Comment by priyanka-tychesoftwares** [comment]
Another client reported this issue: https://tychesoftwares.freshdesk.com/a/tickets/52840

**Comment by pinalj** [comment]
It has been observed on 2 client sites that the plugin was able to auto fix the ID for the guest cart history table in the second attempt, but the notice is still being displayed. 

For the other users, a manual fix was needed.
