### ISSUE TITLE
An error is coming in the error log.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#868]
**Describe the bug**
The below error is coming in the error log:

PHP Warning: Trying to access array offset on value of type int in /wp-content/plugins/woocommerce-abandoned-cart/includes/class-wcal-webhooks.php on line 145, referer: /wp-admin/admin-ajax.php?action=as_async_request_queue_runner&nonce=7d4c0ef807

I tried to set up a webhook on my local site where WP 6.1.1 and PHP 8.0 is present. Then abandoned and recovered the cart but I am unable to replicate this error. I have asked for the steps to the client.

**To Reproduce**
I don't have the steps to replicate this issue currently.

**Expected behavior**
Such an error should not come.

**Screenshots or Video**

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Additional context**
https://wordpress.org/support/topic/not-php-8-1-compatible/

**Comment by Chetna1510** [comment]
One more client has reported this: https://tychesoftwares.freshdesk.com/a/tickets/53552

I'm getting this error noite from my logs. Notice: Trying to access array offset on value of type int in /home/customer/www/gearcost.com/public_html/wp-content/plugins/woocommerce-abandoned-cart/includes/class-wcal-webhooks.php on line 145

The latest wordpress and woocommerce versions and php 7.4
![2023_05_03_11 45 38](https://user-images.githubusercontent.com/15136179/236874040-da9f2c71-f595-4e6d-ae48-5c462b79580d.jpg)

**Comment by Chetna1510** [comment]
One more client has reported this - https://wordpress.org/support/topic/php-warning-433/
