### ISSUE TITLE
The checkout link redirects to the cart page. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#889]
**Describe the bug**
The checkout link redirects to the cart page. 

**To Reproduce**
1. HPOS compatibility enabled 
2. Abandoned the cart as guest users 
3. Reminder email received 
4. Clicked on the checkout link and Open it to another browser then it's redirected to the cart page

The same issue is replicated when I clicked on Product Name on the reminder email. https://app.screencast.com/LaLZSqR0hNXYO

**Expected behavior**
The plugin should redirect to the correct page.

**Comment by nidhitatosaniya** [comment]
ACL does not have the checkout link merge tag. It only allows for the cart link merge tag. Hense I closing this issue.
