### ISSUE TITLE
 Inability to delete expired coupons upon clicking the "Delete" button.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#929]
**Describe the bug**
 Inability to delete expired coupons upon clicking the "Delete" button.

**To Reproduce**
1. Generate some coupons.
2. Some of them are expired or Used 
3. Go to the General setting page, and click on the 'Delete' button.
4. I noticed that the Unquie coupon code is deleted fine but the coupon code which I created manually is not deleted. 

https://app.screencast.com/S41GNBSvCyEz1

**Expected behavior**
Expired and used coupons should be deleted after clicking the 'Delete' button

**Comment by pinalj** [comment]
Not an issue. The setting allows the admin to delete expired and used coupons which are created by the plugin. It will not delete coupons created by other plugins or manually created coupons.
