### ISSUE TITLE
The email template does not activate/deactivate after updating to the latest Git copy.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-abandoned-cart#940]
**Describe the bug**
The email template does not activate/deactivate after updating to the latest Git copy.

**To Reproduce**
1. Take the very latest git copy 
2. Go to the email template page, and try to activate/deactivate the email template but no action is run and the console shows some error.
https://app.screencast.com/XH7PJXsMOoxdo

Note: Even though I tried adding a new email template things are not working. 

**Expected behavior**
The email template must be activated/deactivated.

**Comment by pinalj** [comment]
Closed in https://github.com/TycheSoftwares/woocommerce-abandoned-cart/pull/941
