### ISSUE TITLE
The Abandoned Cart Dashboard is not displaying accurate stats.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#955]
**Describe the bug**
The Abandoned Cart Dashboard is not displaying accurate stats. The "Number of Emails Sent" and "Emails Captured" count do not match the data present on the Abandoned Orders page.  

**To Reproduce**
1. Abandon the carts from the different users such as guest users, registered users, and visitors. 
2. Then check the Abandoned Orders listed there and also, check the View Order details popup. You will notice the count displaying for the "Number of Emails Sent" and "Emails Captured" do not match with the actual data.

**Expected behavior**
The stats displays on the Abandoned Cart Dashboard should match with the actual data. 

**Screenshots or Video**
![site1](https://github.com/TycheSoftwares/woocommerce-abandoned-cart/assets/21337682/260d6bcf-58ee-410e-a122-68e2acf28520)
![site2](https://github.com/TycheSoftwares/woocommerce-abandoned-cart/assets/21337682/c0e3863f-c299-47b0-a3f9-8eceb7208c34)

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/60587

**Comment by pinalj** [comment]
The number of emails captured is incorrect when 
1. there are empty carts present 
2. guest carts which are marked as ignored.

The number of emails sent count is incorrect when
1. create 1 active template
2. abandon some carts
3. the number of emails sent is greater than the count of abandoned carts.
