### ISSUE TITLE
Event schedule does not exist cron error

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/woocommerce-abandoned-cart#971]
**Describe the bug**
A cron error issue was raised by a user on the WP forum, and the user reported that the cron job tried to run an event that does not exist. Error details below:

> Cron reschedule event error for hook: wcal_ts_tracker_send_event, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {“schedule”:”once_in_week”,”args”:[],”interval”:604800}

**Additional context**
[https://wordpress.org/support/topic/event-schedule-does-not-exist-cron-error/](https://wordpress.org/support/topic/event-schedule-does-not-exist-cron-error/)

**Comment by pinalj** [comment]
We are migrating tracking to v2. I'm closing the issue for now as the code where the error came from has now been removed.
