### ISSUE TITLE
Add a filter to increase the limit of data shown on the abandoned carts table beyond 30

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/woocommerce-abandoned-cart#972]
**Is your feature request related to a problem? Please describe.**
We need to create a filter that would allow admins admins/clients to increase the limit currently being applied to the number of data shown per page. The limit is currently 30 but with a filter, site admins can increase it to whatever number (limit) they want.

**Additional context**
[https://wordpress.org/support/topic/per_page-argument-in-url-parameter/#post-17492942](https://wordpress.org/support/topic/per_page-argument-in-url-parameter/#post-17492942)

**Comment by pinalj** [comment]
https://github.com/TycheSoftwares/woocommerce-abandoned-cart/wiki/Miscellaneous---Hooks-&-Filters-present-across-different-features#modify-the-number-of-entries-displayed-on-the-abandoned-orders-page
