### ISSUE TITLE
Add a filter to restrict capturing abandoned carts from a specific email address.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#983]
**Describe the bug**
Add a filter to restrict capturing abandoned carts from a specific email address.

**To Reproduce**

We are unable to replicate this issue at our end. The issue was only occurring on a client's site. 
Fake abandoned carts are being logged on the client's site from the email address 'johnsmith001@storebotmail.joonix.net'.
https://app.screencast.com/wNnUdrvm60ckh

As there is no way in the lite version to restrict capturing carts from the specific email address or domain, we can add a filter for this.

**Additional context**
https://support.tychesoftwares.com/conversation/1854?folder_id=15

**Comment by nidhitatosaniya** [comment]
Added filter name : `wcal_abandoned_cart_user_email`

Add The below code in function.php file
```
add_filter( 'wcal_abandoned_cart_user_email' ,'wcal_abandoned_cart_user_email_callback',10, 2 );
function wcal_abandoned_cart_user_email_callback ( $billing_email_restriction , $billing_email ) {
	$billing_email_restriction = preg_match("/(storebotmail)/i", $billing_email ) ? true : false;
return $billing_email_restriction;

}
```

**Comment by apeksha10** [comment]
After adding the above code, I tried to abandon the cart using Gmail domain, but the cart was not marked as abandoned this is correct but the visitor's cart was captured.

<img width="1158" alt="2024-10-09_15-04-32" src="https://github.com/user-attachments/assets/7f98e549-94ae-4a69-bd66-a42daa81d4d7">

<img width="1042" alt="2024-10-09_15-05-36" src="https://github.com/user-attachments/assets/5d561ebd-e3f6-44b2-8427-318a8845d35c">


Hence I re-open this issue.

**Comment by apeksha10** [comment]
The above issue is still replicated in the latest copy,
<img width="1213" alt="2024-10-10_15-35-15" src="https://github.com/user-attachments/assets/ee0fbac5-16da-49d3-9cb0-a979e4b2482e">

Hence I re-open this issue.
