### ISSUE TITLE
Webhooks not working with the latest version of WooCommerce

### ISSUE THREAD

**Issue by oluisrael11** [TycheSoftwares/woocommerce-abandoned-cart#984]
**Describe the bug**
There has been a report from one of our users about being unable to send abandoned cart data via webhooks. This happened to the affected user after updating the WooCommerce plugin to the latest version.

At the moment, we need to fix this and then test webhooks with the latest WooCommerce release.

**Expected behavior**
Abandoned cart data should be properly and correctly sent via webhooks.

**Additional context**
[https://wordpress.org/support/topic/webhook-not-working-5/](https://wordpress.org/support/topic/webhook-not-working-5/)
[https://support.tychesoftwares.com/conversation/3886?folder_id=4](https://support.tychesoftwares.com/conversation/3886?folder_id=4)

**Comment by oluisrael11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub issue - 984](https://trello.com/c/pRJDfd8y/19-github-issue-984)

**Comment by ilovefreesw** [comment]
I am having this issue as well. I am able to receive the product data but not the user data in the webhook. The user detail fields are blank.
![image](https://github.com/TycheSoftwares/woocommerce-abandoned-cart/assets/77317006/345583c6-1153-49bd-b28c-c70d3b31e3af)

**Comment by oluisrael11** [comment]
@ilovefreesw I have retested this on my end and with v9.6.0 and I can confirm that the user data was added to the webhook alongside the the product data.

![image](https://github.com/TycheSoftwares/woocommerce-abandoned-cart/assets/12012702/07db68ee-eda4-4bae-a6a5-df7987a7cde8)

Can you update the WP, Woo, and Abandoned Cart Pro plugins to the following highlighted below and retry the entire process?

WordPress Version: 6.5.3
WooCommerce Version: 8.8.3
Abandoned Cart Pro version: 9.7.1

**Comment by ilovefreesw** [comment]
Sorry coming late but still doesn't work for me. I have pro version by the way. The webhook payload doesn't include user information. The billing and shipping fields are empty.

![image](https://github.com/user-attachments/assets/e29745d7-437d-4d91-a123-ad4639f42205)

We also use cartflows .. is there any compatibility issues ?

Details:

WordPress version: 6.6.1
WooCommerce Version: 9.2.3
Abandon Cart Pro Version: 9.10.0

**Comment by oluisrael11** [comment]
@ilovefreesw can you confirm if the user information were entered on the checkout page before the cart was abandoned? The test on my end showed the user information added to the webhook payload. See the image below for reference:

![image](https://github.com/user-attachments/assets/4874fefd-d722-47fb-b68e-976ac2b99db4)

Some parts of the information were blurred out but the first two to three characters are visible.

**Comment by ilovefreesw** [comment]
The abandoned cart mails are going just fine....it's just that the data is missing in the webhooks. I can see the user information on the dashboard. We are also using the add to cart popup forms offered by the plugin to capture the user email and phone number beforehand. That is also not being added to the webhook payload.

**Comment by nidhitatosaniya** [comment]
We have fixed this above issue on client's staging site by executing the following SQL Query:
**ALTER TABLE `wp_ac_guest_abandoned_cart_history` AUTO_INCREMENT = 63000000;**
